#pragma once

#include "JW2DEngine.h"
#include "Scene.h"
#include "GameObject.h"
#include "Transform.h"
#include "BoxRenderer.h"
#include "BoxCollider.h"
#include "CircleRenderer.h"
#include "CircleCollider.h"
#include "SpriteRenderer.h"
#include "Rigidbody.h"
#include "Player.h"
//#include "EnemyController.h"
#include "PlayerHeadTrigger.h"
#include "Animator.h"
#include "Text.h"
#include "UIManager.h"
#include "Item.h"
#include "MovableTile.h"
#include "GetThroughTile.h"
#include "BrokenWall.h"
#include "Hurdle.h"
#include "Camera.h"
#include "CameraController.h"
#include "AnimClipLoader.h"
#include "Lazer.h"

#define AnimClipPath(x) "AnimClip\\" + string(x) + ".json"